FROM ubuntu:18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    emacs \
    git \
    wget \
    ca-certificates \
    curl \
    nmap \
    less \
    gcc \
    g++ \
    libmysqlclient-dev \
    python3.6 \
    python3.6-dev \
    python3-distutils \
    python3-mysqldb
RUN cd /tmp/ && wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y nodejs

RUN apt-get install -y gnupg2
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y yarn

RUN apt-get install -y sudo lsof make
RUN pip3 install arrow

#RUN yarn add truffle && yarn run truffle init
CMD yarn run zos compile && yarn lint && yarn run zos check && yarn truffle test

WORKDIR /code/
ADD yarn.lock package.json /code/
#RUN yarn add @openzeppelin/cli @truffle/hdwallet-provider truffle-hdwallet-provider-privkey@web3-one zos
RUN yarn
ADD . /code/
# TODO init usingtellor RUN git clone git@github.com:tellor-io/usingtellor.git && cd usingtellor
RUN git submodule update --init && rm contracts/usingtellor/flatfiles/usingTellor_flat_2020_05_17.sol